# -*- coding: utf-8 -*-
"""candidate_elimination.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pUStsUZVgWBBAjYc2ym0T7V7ctjF-Vju
"""

def candidate_elimination(data):
    # Last column is the target
    attributes = len(data[0]) - 1

    # Most specific hypothesis
    S = ['0'] * attributes

    # Most general hypothesis
    G = [['?'] * attributes]

    for example in data:
        x = example[:-1]
        target = example[-1]

        if target == 'Yes':
            # Remove general hypotheses that don't cover the positive example
            G = [g for g in G if covers(g, x)]

            # Generalize S to cover the positive example
            for i in range(attributes):
                if S[i] == '0':
                    S[i] = x[i]
                elif S[i] != x[i]:
                    S[i] = '?'

        else:  # Negative example
            new_G = []

            for g in G:
                if covers(g, x):
                    # Specialize G to exclude the negative example
                    for i in range(attributes):
                        if g[i] == '?':
                            if S[i] != '?' and S[i] != '0':
                                new_h = g.copy()
                                new_h[i] = S[i]
                                new_G.append(new_h)
                else:
                    new_G.append(g)

            G = new_G

    return S, G


def covers(hypothesis, example):
    for h, x in zip(hypothesis, example):
        if h != '?' and h != x:
            return False
    return True


# Example dataset
data = [
    ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same', 'Yes'],
    ['Sunny', 'Warm', 'High',    'Strong', 'Warm', 'Same', 'Yes'],
    ['Rainy', 'Cold', 'High',    'Strong', 'Warm', 'Change', 'No'],
    ['Sunny', 'Warm', 'High',    'Strong', 'Cool', 'Change', 'Yes']
]

S, G = candidate_elimination(data)

print("Specific Boundary (S):")
print(S)

print("\nGeneral Boundary (G):")
for hypothesis in G:
    print(hypothesis)