# -*- coding: utf-8 -*-
"""candidate_elimination.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pUStsUZVgWBBAjYc2ym0T7V7ctjF-Vju
"""

def candidate_elimination(data):
    # Last column is the target
    attributes = len(data[0]) - 1

    # Most specific hypothesis
    S = ['0'] * attributes

    # Most general hypothesis
    G = [['?'] * attributes]

    for example in data:
        x = example[:-1]
        target = example[-1]

        if target == 'Yes':
            # Remove general hypotheses that don't cover the positive example
            G = [g for g in G if covers(g, x)]

            # Generalize S to cover the positive example
            for i in range(attributes):
                if S[i] == '0':
                    S[i] = x[i]
                elif S[i] != x[i]:
                    S[i] = '?'

        else:  # Negative example
            new_G = []

            for g in G:
                if covers(g, x):
                    # Specialize G to exclude the negative example
                    for i in range(attributes):
                        if g[i] == '?':
                            if S[i] != '?' and S[i] != '0':
                                new_h = g.copy()
                                new_h[i] = S[i]
                                new_G.append(new_h)
                else:
                    new_G.append(g)

            G = new_G

    return S, G


def covers(hypothesis, example):
    for h, x in zip(hypothesis, example):
        if h != '?' and h != x:
            return False
    return True


# Example dataset
data = [
    ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same', 'Yes'],
    ['Sunny', 'Warm', 'High',    'Strong', 'Warm', 'Same', 'Yes'],
    ['Rainy', 'Cold', 'High',    'Strong', 'Warm', 'Change', 'No'],
    ['Sunny', 'Warm', 'High',    'Strong', 'Cool', 'Change', 'Yes']
]

S, G = candidate_elimination(data)

print("Specific Boundary (S):")
print(S)

print("\nGeneral Boundary (G):")
for hypothesis in G:
    print(hypothesis)

import pandas as pd

# ============================================================
# 1. CREATE THE DATASET
# ============================================================

data = [
    ['Sunny', 'Hot', 'High', 'Weak', 'No'],
    ['Sunny', 'Hot', 'High', 'Strong', 'No'],
    ['Overcast', 'Hot', 'High', 'Weak', 'Yes'],
    ['Rain', 'Mild', 'High', 'Weak', 'Yes'],
    ['Rain', 'Cool', 'Normal', 'Weak', 'Yes'],
    ['Rain', 'Cool', 'Normal', 'Strong', 'No'],
    ['Overcast', 'Cool', 'Normal', 'Strong', 'Yes'],
    ['Sunny', 'Mild', 'High', 'Weak', 'No'],
    ['Sunny', 'Cool', 'Normal', 'Weak', 'Yes'],
    ['Rain', 'Mild', 'Normal', 'Weak', 'Yes'],
    ['Sunny', 'Mild', 'Normal', 'Strong', 'Yes'],
    ['Overcast', 'Mild', 'High', 'Strong', 'Yes'],
    ['Overcast', 'Hot', 'Normal', 'Weak', 'Yes'],
    ['Rain', 'Mild', 'High', 'Strong', 'No']
]

columns = [
    'Outlook',
    'Temperature',
    'Humidity',
    'Wind',
    'Play'
]

df = pd.DataFrame(data, columns=columns)

print("============================================================")
print("DATASET")
print("============================================================")
print(df)


# ============================================================
# 2. PREPARE DATA
# ============================================================

training_data = df.values.tolist()

num_attributes = len(training_data[0]) - 1


# ============================================================
# 3. FUNCTION TO CHECK WHETHER A HYPOTHESIS COVERS AN EXAMPLE
# ============================================================

def covers(hypothesis, example):

    for h, x in zip(hypothesis, example):

        # '?' means any value is accepted
        if h != '?' and h != x:
            return False

    return True


# ============================================================
# 4. CANDIDATE ELIMINATION ALGORITHM
# ============================================================

def candidate_elimination(data):

    # --------------------------------------------------------
    # S = Most Specific Hypothesis
    # --------------------------------------------------------
    S = ['0'] * num_attributes

    # --------------------------------------------------------
    # G = Most General Hypothesis
    # --------------------------------------------------------
    G = [['?'] * num_attributes]

    print("\n\n============================================================")
    print("CANDIDATE ELIMINATION")
    print("============================================================")

    # Process every training example
    for step, example in enumerate(data, start=1):

        x = example[:-1]
        target = example[-1]

        print(f"\n\nStep {step}")
        print("-" * 60)

        print("Example :", x)
        print("Target  :", target)

        # ====================================================
        # POSITIVE EXAMPLE
        # ====================================================

        if target == 'Yes':

            print("\nPositive example → Generalize S")

            # Remove hypotheses from G that don't cover
            # the positive example
            G = [
                g for g in G
                if covers(g, x)
            ]

            # Generalize S
            for i in range(num_attributes):

                # If S has no value yet
                if S[i] == '0':
                    S[i] = x[i]

                # If S and example have different values
                elif S[i] != x[i]:
                    S[i] = '?'

        # ====================================================
        # NEGATIVE EXAMPLE
        # ====================================================

        else:

            print("\nNegative example → Specialize G")

            new_G = []

            for g in G:

                # If G covers the negative example,
                # it must be specialized
                if covers(g, x):

                    for i in range(num_attributes):

                        if g[i] == '?':

                            # S provides a value that can be
                            # used to specialize G
                            if S[i] != '?' and S[i] != '0':

                                new_h = g.copy()

                                new_h[i] = S[i]

                                new_G.append(new_h)

                else:
                    # This hypothesis already excludes
                    # the negative example
                    new_G.append(g)

            G = new_G

        # ====================================================
        # DISPLAY CURRENT BOUNDARIES
        # ====================================================

        print("\nSpecific Boundary (S):")
        print(S)

        print("\nGeneral Boundary (G):")

        if len(G) == 0:
            print("[]")
        else:
            for hypothesis in G:
                print(hypothesis)

    return S, G


# ============================================================
# 5. RUN THE ALGORITHM
# ============================================================

S, G = candidate_elimination(training_data)


# ============================================================
# 6. FINAL RESULT
# ============================================================

print("\n\n============================================================")
print("FINAL RESULT")
print("============================================================")

print("\nSpecific Boundary (S):")
print(S)

print("\nGeneral Boundary (G):")

if len(G) == 0:
    print("[]")
else:
    for hypothesis in G:
        print(hypothesis)